@startuml
!pragma teoz true
autonumber
' autoactivate on
skinparam defaultFontSize 20

' box HPC Site
actor User1 as u1
participant HPC1 as h1
' end box
' box QC-HPC Coscheduler
participant Sched as q << (Q, #ADD1B2) >>
' end box
' box HPC Site
participant HPC2 as h2
actor User2 as u2
' end box

activate q

u1 -> h1 : Job Sub \t
h1 -> q : QC Req \t\t\t\t
' q -> q : QC Check (OK)
' hnote over q #FFBBBB: SF++
{start1} q -> h1 : QC <color #green>OK</color> 

activate q #FFBBBB
activate h1 #DarkSalmon

u2 -> h2 : Job Sub \t
h2 -> q : QC Req \t\t\t\t
' q -> q : QC Check (NG)
q -> h2 : QC <color #red>NG</color>

{end1} h1 -> q : QC FIN
deactivate h1
deactivate q 
{start1} <-> {end1} : Job Run
' hnote over q : SF--

h2 -> q : QC (Re)Req 
' q -> q : QC Check (OK)
' hnote over q #FFBBBB: SF++
{start2} q -> h2 : QC <color #green>OK</color> 
activate q #FFBBBB
activate h2 #DarkSalmon
{end2} h2 -> q : QC FIN
deactivate h2
deactivate q 
{start2} <-> {end2} : Job Run
' hnote over q : SF--

@enduml